---
# handlers file for ansible-zabbix-server
- name: Start Service
  systemd:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - '{{services}}'
  when: inventory_hostname in groups['zabbix_server']

- name: restart postgresql
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted

