---
- name: Install epel
  yum:
    name: epel-release
    state: present

- name: Install pip
  yum:
    name: python-pip
    state: present

- name: Install python expect
  pip:
    name: pexpect

- name: Import Zabbix RPM Key
  rpm_key:
    state: present
    key: "{{ zabbix_key_url }}"
  register: zabbixkey

- name: wait 5 sec to finish
  pause:
    seconds: 5
  when: zabbixkey.changed

- name: Get Zabbix RPM
  yum:
    name: "{{ zabbix_rpm_url }}"
    state: present
  register: zabbixrpm

- name: wait 5 sec to finish
  pause:
    seconds: 5
  when: zabbixrpm.changed

- name: Install Zabbix
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - "{{ zabbix_server_install }}"
  notify:
    - Start Service
